[Experimental]alternative for using external dependencies implementation
ttypic/swift-klib-plugin pull request #49
Opened 2024-11-04 17:12 UTC by frankois944

Based on #47

- Using the command line instead of String manipulation
- Adding local spm can't be done by command line, so I did it manually
- Adding platforms can't be done by command line, so I did it manually
- Adding complex package support (like firebase : see tests)
- Adding toolsVersion 
- simplify the swift build command

See the new tests for new features

To be done : change the way the version of a spm is set, the command line has limited possibility.

2024-11-05 07:49 UTC, frankois944 commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/task/CompileSwiftTask.kt
> +        execOperations.exec {
I think the error ouput of a command should be visible by the user of the plugins in all case, it's really important for knowing what were wrong with swift spm.
But, it's currently not the case.

2024-11-05 07:49 UTC, frankois944 commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/task/CompileSwiftTask.kt
> +            "--triple",
using triplet make easy the compiler to choose the correct target

2024-11-05 07:50 UTC, frankois944 commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/templates/CreatePackageSwift.kt
> +            // can't do inclusive range from command line
we can't do inclusive range from command line
but I think it's better to use up-to-next-minor-from.
need some rework here

2024-11-05 07:51 UTC, frankois944 commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/templates/CreatePackageSwift.kt
> +            // can't do inclusive range from command line
command usage 
`swift package add-dependency <dependency> [--exact <exact>] [--revision <revision>] [--branch <branch>] [--from <from>] [--up-to-next-minor-from <up-to-next-minor-from>] [--to <to>]`

2024-11-06 08:05 UTC, frankois944 commented
I added the capability to set the toolsversion.
By default, it's the latest swift version.

2024-11-11 09:53 UTC, frankois944 commented
@IlyaGulya Some feedback?

2024-11-11 13:35 UTC, IlyaGulya commented
@frankois944 sorry, quite busy this week. I hope to take a look this weekend

2024-11-21 04:27 UTC, tareksabry1337 commented
Anything on this? 👀

2024-11-23 19:01 UTC, IlyaGulya requested changes
@frankois944 
Thanks for the PR!
Sorry for the late response.
Overall, love to see more tests, but I have some concerns about API changes and cli usage approach, so I've left some comments.
Waiting for your response.

2024-11-24 08:16 UTC, frankois944 commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/SwiftPackageDependency.kt
> +                require(name.isNotEmpty() && name.indexOfFirst { it.isBlank() } == -1) { "Package name cannot be blank" }
`name` is now a `List<String>` and not a `String`, so I can't use `isNotBlank`.

I replaced `name.indexOfFirst { it.isBlank() } == -1` with `!name.contains("")`, it's simpler.

2024-11-24 08:20 UTC, frankois944 commented on plugin/src/functionalTest/kotlin/io/github/ttypic/swiftklib/gradle/fixture/SwiftKlibTestFixture.kt
> +    val _minWatchos = notNull<String>()
I change from a `Int` to a `String`; it has too much limitation.
For example, we can't use this kind of version `macos = "10.15.1"`, this is possible to set in the Package manifest.

I don't think it's a big deal, as it's just a type of the input to change.

2024-11-24 08:34 UTC, frankois944 commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/templates/CreatePackageSwift.kt
> +) {
Using the swift CLI, make sure the current (and future) format is correct, as we don't need to do some migration, there are a lot of cases to manage and the complex ones are managed by the CLI.

I'm fully aware of the limitation of the CLI which doesn't propose all functionality, but at least we don't need to check the structure.

I just think using a template will make the code more complex.

2024-11-24 09:59 UTC, frankois944 commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/templates/CreatePackageSwift.kt
> +) {
FYI, for my next PR about local/remote binary package, I did some refactoring on the string manipulation and simplified it.

2024-11-24 12:48 UTC, IlyaGulya commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/templates/CreatePackageSwift.kt
> +) {
The main benefit of templating is it's self-explanatory.

Can you please explain which complex cases are being managed by CLI?
From my perspective Package.swift structure isn't that complex

2024-11-24 13:19 UTC, frankois944 commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/templates/CreatePackageSwift.kt
> +) {
The complexity come from the type of dependancy, the CLI give some help; and I'm suspecting xcode is using the CLI.

We can replace the command line by a template, but we need to keep an eye of the Manifest evolution more closely.

Just say, it safer to use a tool who can (almost) respect the format than making one.

2024-11-24 13:39 UTC, IlyaGulya commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/SwiftPackageDependency.kt
> +                require(name.isNotEmpty() && name.indexOfFirst { it.isBlank() } == -1) { "Package name cannot be blank" }
Sorry, missed this.
I think you should return `isBlank` then, like this:
```
require(name.isNotEmpty() && name.none { it.isBlank() }) { "Package name cannot be blank" }
```

2024-11-24 14:26 UTC, frankois944 commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/SwiftPackageDependency.kt
> +                require(name.isNotEmpty() && name.indexOfFirst { it.isBlank() } == -1) { "Package name cannot be blank" }
Yes, didn't know this one, it's updated

2024-11-24 15:27 UTC, frankois944 commented on plugin/src/main/kotlin/io/github/ttypic/swiftklib/gradle/templates/CreatePackageSwift.kt
> +) {
@IlyaGulya I don't mind to change to a template instead of the CLI.

2024-11-26 09:53 UTC, frankois944 commented
@IlyaGulya I move to the template
The major issue is the format stuck to a specific swift tool version, I put the default version at 5.6.
If the user set another tools version, the manifest can be broken as the API has been changed.

2024-11-26 17:56 UTC, IlyaGulya commented
@frankois944 do you know if swift tools follow semantic versioning?
Can we be sure that breaking changes happen only on major releases?
I think currently that should not be an issue, we can always support new tools version, API surface relevant to this plugin does not seem to be large

2024-11-26 18:22 UTC, frankois944 commented
> @frankois944 do you know if swift tools follow semantic versioning? Can we be sure that breaking changes happen only on major releases? I think currently that should not be an issue, we can always support new tools version, API surface relevant to this plugin does not seem to be large

The Manifest API depends on the swift version declared in the first line.
I didn't follow API evolution, but I think we will see some warning if we have the need to update the template.
We will need to upgrade the template when this version won't be supported by the compiler.
For now, I guess, this template is enough.

2024-11-27 18:03 UTC, IlyaGulya approved these changes

2024-11-27 18:04 UTC, merged

2024-11-27 18:04 UTC, IlyaGulya commented
@frankois944 merged
Thank you for the contribution!
I will try to finish this draft this weekend and merge to master (and maybe provide a SNAPSHOT build)

2025-01-17 17:46 UTC, sgozdzik commented
> @frankois944 merged Thank you for the contribution! I will try to finish this draft this weekend and merge to master (and maybe provide a SNAPSHOT build)

Thanks for good work with library! Any idea when you will have some time to release some snapshot build?